# Generated by Django 5.2.8 on 2025-11-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='user@django.com', max_length=150)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
